### ISSUE TITLE
Pool table has no interactive capability

### ISSUE THREAD

**Issue by AndrewMM1337** [VRCBilliards/vrcbce#115]
I imported Udonsharp, cyanemu, the latest build, tried all 4 prefabs, all of them lack the ability to start the game or interact with the table at all. I'm not sure if this has anything to do with it but under VRCBCE Metal (Esnya) prefab in the hierarchy, VRCBCE Menu (Esyna) and UI Toggle have no udon program sources in udon behavior.

**Comment by Legoman99573** [comment]
are you using the one in releases, master branch, or one of the 2 PRs?

**Comment by AndrewMM1337** [comment]
yeah looking at it further it seems that by default there's no udonbehavior scripts attached to the prefab at all, however they do exist. I just have no idea which scripts go into which areas. I can't think of a reason why for me it doesn't do it automatically. previous version 1.3.1 works fine.

**Comment by Legoman99573** [comment]
Did you try removing VRCBillards folder then reimport? Usually that solves the problem with lost udon behavior references

**Comment by AndrewMM1337** [comment]
So I did that, somehow the standard pool table now works! However the metal one, still a no-go. The udon behavior scripts are detached and I have no idea which ones go where. Starting to seem like one of those ghost in the machine problems, do appreciate your help though. I am attempting to use the regular table and just put a metal one as the model instead but I don't think ill have full functionality (4 ball pocket blockers, seeing balls roll down the bottom, etc)

**Comment by AndrewMM1337** [comment]
If i knew the name of the script that belongs in each of all of the missing udo behaviors then i could "manually (drag-drop) " fix it

**Comment by ghost0001** [comment]
I just re-downloaded the asset package today (the 13th) after initially downloading it on the 11th. The table still is not interactable.
