### ISSUE TITLE
CSharp does exist in the name space Microsoft.CodeAnalysis

### ISSUE THREAD

**Issue by RavuRaku** [VRCBilliards/vrcbce#136]
I'm somewhat new to making VRChat worlds. When I import the Billiards prefab into my world, I get 
240 errors with the majority of the errors being that "CSharp does exist in the name space Microsoft.CodeAnalysis". I wasn't able to find any answers online and there was someone else having the same issue online with someone responding with they should contact the creator, so here I am also looking for an answer.
![Screenshot 2021-12-27 203951](https://user-images.githubusercontent.com/96755422/147518416-9642346c-2fe5-4839-9a01-1000de52bccf.png)

**Comment by Legoman99573** [comment]
Check what you have imported in the project as there is some script that conflicts with UdonSharp. Start a new project and just only import sdk 3, udon sharp, and the pool table prefab and then slowly import other scripts. It should narrow down what script or bundle is causing it.

**Comment by RavuRaku** [comment]
Thank you for the response. While adding scripts, I decided to retry adding it into my main project and it appears the error occurs when I try to import the Billiards stuff into a folder in assets rather than importing to assets itself. I no longer get any errors, but I do get some warnings. It appears these are preventing the start button from working in Build&Test.
![image](https://user-images.githubusercontent.com/96755422/147525912-24146216-9bdc-46e7-8e77-2c918dab2775.png)
