### ISSUE TITLE
Cannot compile world with this asset.

### ISSUE THREAD

**Issue by TrashDwellingTroll** [VRCBilliards/vrcbce#139]
I am getting this error when attempting to compile a world with this asset in it...
**Assets\VRCBilliardsCE\Scripts\PoolStateManager.cs(575,10): error CS0246: The type or namespace name 'UdonSynced' could not be found (are you missing a using directive or an assembly reference?)**

I built a new world with just VRC SDK 3 Worlds, and got this instead...
**Assembly 'Assets/Udon/Editor/External/VRC.Udon.EditorBindings.dll' will not be loaded due to errors:
Unable to resolve reference 'Cinemachine'. Is the assembly missing or incompatible with the current platform?**

Is there a required addon that I am missing or anything?

**Comment by Legoman99573** [comment]
start a new project and import sdk3, then udonsharp, then the pool table prefab. if nothing else hapens, then its most likely a script causing conflicts

**Comment by TrashDwellingTroll** [comment]
That worked, I can now compile with the asset. Thank you I was missing UdonSharp
