### ISSUE TITLE
Winner is the opposite player even if no foul ball occurs

### ISSUE THREAD

**Issue by Legoman99573** [VRCBilliards/vrcbce#145]
Not sure how this slipped during the rewrite of the pocketing functionality for 8ball. Thought I would throw it out there. Using https://github.com/VRCBilliards/vrcbce/commit/a13907b8b4a9cc65eced1c9e6241e4e6ca4befd2 atm.

**Comment by FairlySadPanda** [comment]
Bad timing as I am currently on holiday. Need a more specific bug report than the title so I can drill down and fix it when I am able to do VRC work again on Friday.

**Comment by FairlySadPanda** [comment]
Fix should be in on master, good spot

**Comment by Legoman99573** [comment]
Late response, but it has resolved the issue. No need to keep this issue open since https://github.com/VRCBilliards/vrcbce/commit/67368d8b21e59f4b53d1b01205a0ff482f277728 resolved it.
