### ISSUE TITLE
Rear cue control not recognising trigger pull.

### ISSUE THREAD

**Issue by Traediras** [VRCBilliards/vrcbce#172]
Using VCC 2.0.0, SDK 3.1.11, U# 1.1.7, VRCBilliards 1.6.0 package from master branch.

VR controls for the front of the cue works, however the control for the back of the cue does not recognise the trigger being pulled, preventing it from locking in place and consequently being unable to strike the ball.

Occurs both with left and right hands. Works as expected in desktop mode. Problem occurs on all tables.

**Comment by Ariexe** [comment]
I also have this issue

**Comment by FairlySadPanda** [comment]
Fixed today in latest commit. Apologies, this should have been caught during testing.
