### ISSUE TITLE
Toggling the Table using a UI Toggle

### ISSUE THREAD

**Issue by Keatersz** [VRCBilliards/vrcbce#174]
I cant seem to toggle the table and its components on and off using Unity's UI Toggle.

Unsure if its an issue on my end of unity or the assets end, thought id message here to see.

**Comment by Reava** [comment]
There is a toggle for the table's UI included with it, what do you mean by "Unity's UI Toggle" ? look for toggling the canvas if you want something different than the table's included toggle.

**Comment by Reava** [comment]
Then that's not related to the table, your UI toggle is just not working. Look up how to make a simple UI toggle in unity, there are tons of tutorial for that.

**Comment by Metamaniac** [comment]
Reava is correct, as long as you are referencing the parent GameObject properly, there should be no issues assuming your toggle logic is setup correctly. Closing this as it's unrelated to our prefab specifically (I hope you end up figuring out the issue on your end!)

**Comment by Keatersz** [comment]
I _was_ sure that it was the assets end, but you're right I found the issue on my end.
