### ISSUE TITLE
Changing ball material for gameplay

### ISSUE THREAD

**Issue by atomiklan** [VRCBilliards/vrcbce#175]
For some reason, when I attempt to swap the ball material from the orange and blue balls to the realistic texture, it works for the static pregame arrangement of balls, but once the game starts, it defaults back to blue and orange. I have dug through seemingly every option and cant see what I have done wrong. Perhaps I should not be manually switching textures. Perhaps there is an actual setting somewhere I have missed to toggle between the different customization. I for the life of me cannot find it though and I don't see any documentation on customization outside the initial setup guide. Is this a bug or intended behavior?

**Comment by FairlySadPanda** [comment]
If you can't figure it out, I'd class that as a bug - this stuff should be easy. At the moment I'd probably outright swap the textures in the prefab.

**Comment by Metamaniac** [comment]
@atomiklan In the "Materials" section of the UdonBehavior, there should be a dropdown called "Sets" which contains the references to the textures that get swapped depending on which gamemode you select at the beginning. If you want to change the textures of the balls *at runtime*- do it there. Changing the material for the static objects themselves only makes them look differently before a game is played (which is often *also* desirable for worlds with custom skins)
![image](https://github.com/VRCBilliards/vrcbce/assets/6299186/427b10a2-8b51-4815-a61f-13020a729536)
