### ISSUE TITLE
Pool Parlor Physics

### ISSUE THREAD

**Issue by S0LDIII3R** [VRCBilliards/vrcbce#192]
Hi,
im trying to find where the table is situated for the pool parlor physics
is it mentionned in the credits for 1.6 but where do i get my hands on it ?

**Comment by Legoman99573** [comment]
https://codeload.github.com/VRCBilliards/vrcbce/zip/refs/heads/master/vrcbce-master.zip should grab the latest master branch of the project. Just put ``com.vrcbilliards.vrcbce`` in the ``Packages`` folder instead of assets.

**Comment by S0LDIII3R** [comment]
i did download the latest branch indeed and grabbed the com.vrcbilliards.vrcbce in the Packages folder.
But i cant seem to find the Pool parlor variant.
![image](https://github.com/VRCBilliards/vrcbce/assets/154616033/6451f061-129b-4d7b-815e-e7e355c55c78)

**Comment by Legoman99573** [comment]
The physics is implemented in all the tables with some back port changes made, like getting it out of 0,0,0 in a world so it can work in any location and any rotation

**Comment by S0LDIII3R** [comment]
alright thank u ^^

**Comment by FairlySadPanda** [comment]
Thanks @Legoman99573 for resolving this
