### ISSUE TITLE
White ball pickup incorrect reset.

### ISSUE THREAD

**Issue by MrDummyNL** [VRCBilliards/vrcbce#38]
Today v1.1.1 testing, and there is one big problem. The white ball pickup showed out of nothing and stays on for other team member, but even too for other team member.
And it repeat again with new game round. So if other player complete white ball positioning, it doesnt go away for others. Probably sync issue.
Also at begin game, where player may move freely, it doesnt go away for others.

1v1 gameplay has less problems, so team mode has weird bugs.

This must solved immediately.

**Comment by MrDummyNL** [comment]
You know, version 1.1.0 has also little white ball "replace" bug noticed, but 1.1.1 is way more worser compared to 1.1.0. So much staying there and not removed properly. Many times showed in the game.
This bug makes whole pool pretty broken and very confusing to play for others.

I think you might need add extra checkpoints in code to make sure it's removed by others and not stay there all the time. I know this is hard to code in big script which is made by other. Good luck.

**Comment by FairlySadPanda** [comment]
This should be fixed by now. I'll close this in a few days unless it isn;t.
